parameters:
    ten24_twig.extension.diff.class: Ten24\Twig\Extension\DiffExtension

services:
    ten24_twig.extension.diff:
        class: '%ten24_twig.extension.diff.class%'
        public: false
        tags:
            - { name: twig.extension }