parameters:
    ten24_twig.extension.inflector.class: Ten24\Twig\Extension\InflectorExtension

services:
    ten24_twig.extension.inflector:
        class: '%ten24_twig.extension.inflector.class%'
        public: false
        tags:
            - { name: twig.extension }